# Numpy Operations

In [12]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

#elementwise operations.
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]


In [13]:
#loop vs vectorized execution.
big_array = np.arange(1_000_000)

%timeit [x * 2 for x in big_array]
%timeit big_array * 2

73.2 ms ± 1.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
964 μs ± 18.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Dataset Loading

In [14]:
import pandas as pd

df = pd.read_csv("../data/starter_data.csv")
df.info()
df.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   category  10 non-null     object
 1   value     10 non-null     int64 
 2   date      10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes


category  value        date
0        A     10  2025-08-01
1        B     15  2025-08-02
2        A     12  2025-08-03
3        B     18  2025-08-04
4        C     25  2025-08-05

# Summary Statistics

In [15]:
df.describe()

value
count  10.000000
mean   17.600000
std     7.381659
min    10.000000
25%    12.250000
50%    14.500000
75%    23.250000
max    30.000000

In [16]:
df.groupby("category")["value"].mean()

category
A    11.500000
B    15.666667
C    27.666667
Name: value, dtype: float64

#Save Outputs

In [17]:
df.describe().to_csv("../data/processed/summary.csv")

# Reuseable Functions

In [18]:
def get_summary_stats(df):
    return df.describe()